# My kitty conf

# Font

font_family "FiraCode Nerd Font"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13

# Colors

color0 #2B1A18
color1 #B53F2F
color2 #3F6E52
color3 #D29B31
color4 #35597C
color5 #8E3F50
color6 #3F8A84
color7 #E0D2B8

color8 #4B3A35
color9 #D1533E
color10 #59A273
color11 #E4B94C
color12 #4F7FB5
color13 #944356
color14 #56B0B8
color15 #FAF4E8

background #1E1412
foreground #FAF4E8
