set -g mouse on
setw -g mode-keys vi
set -g base-index 1
set -g history-limit 100000

# Use Escape as prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Reload config
bind r source-file ~/.tmux.conf \; display-message "reloaded"

# Splits
bind h split-window -h
bind v split-window -v

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Windows (prefix + number)
bind '"' select-window -t 1
bind « select-window -t 2
bind » select-window -t 3
bind ( select-window -t 4
bind ) select-window -t 5
bind @ select-window -t 6
bind + select-window -t 7
bind - select-window -t 8
bind / select-window -t 9
bind * select-window -t 10
